require "minitest/utils"
require "minitest/utils/rails"
require "minitest/utils/rails/locale"
require "minitest/utils/capybara/screenshot_on_failures"
require "minitest/utils/capybara/chrome_headless"
